# Generated by Django 3.0.6 on 2023-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productMainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=400)),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
