# Generated by Django 3.0.6 on 2023-01-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productMainModel')),
            ],
        ),
        migrations.CreateModel(
            name='productColourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colour', models.CharField(max_length=20)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productMainModel')),
            ],
        ),
    ]
